replicaCount: 2

image:
  repository: IMAGE_NAME
  pullPolicy: Always
  tag: "IMAGE_TAG"

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    cpu: 40m
    memory: 64Mi
  requests:
    cpu: 40m
    memory: 64Mi

